/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyChild {
    }
    interface MyParent {
    }
}
declare global {
    interface HTMLMyChildElement extends Components.MyChild, HTMLStencilElement {
    }
    var HTMLMyChildElement: {
        prototype: HTMLMyChildElement;
        new (): HTMLMyChildElement;
    };
    interface HTMLMyParentElement extends Components.MyParent, HTMLStencilElement {
    }
    var HTMLMyParentElement: {
        prototype: HTMLMyParentElement;
        new (): HTMLMyParentElement;
    };
    interface HTMLElementTagNameMap {
        "my-child": HTMLMyChildElement;
        "my-parent": HTMLMyParentElement;
    }
}
declare namespace LocalJSX {
    interface MyChild {
    }
    interface MyParent {
    }
    interface IntrinsicElements {
        "my-child": MyChild;
        "my-parent": MyParent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-child": LocalJSX.MyChild & JSXBase.HTMLAttributes<HTMLMyChildElement>;
            "my-parent": LocalJSX.MyParent & JSXBase.HTMLAttributes<HTMLMyParentElement>;
        }
    }
}
